from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


GENERATED_MARKER = "<!-- Generated by ai-tooling v2 from .cursor/. Do not edit. -->"
TOKEN_PATTERN = re.compile(r"\{\{([A-Z][A-Z0-9_]*)\}\}")
SKIP_NAMES = {".DS_Store", "__pycache__"}


@dataclass(frozen=True)
class Manifest:
    schema_version: int
    project_name: str
    profile: str
    enabled_policies: tuple[str, ...]
    detected: dict[str, object]
    pending_questions: tuple[object, ...]

    @property
    def project_slug(self) -> str:
        value = re.sub(r"[^A-Za-z0-9._-]+", "-", self.project_name.strip().lower())
        return value.strip("-.") or "project"


def load_manifest(target: Path) -> Manifest:
    path = target / ".cursor" / "ai-tooling.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(".cursor/ai-tooling.json 必须是 JSON 对象")
    if value.get("schemaVersion") != 2:
        raise ValueError("manifest schemaVersion 必须为 2")
    project_name = value.get("projectName")
    profile = value.get("profile")
    if not isinstance(project_name, str) or not project_name.strip():
        raise ValueError("manifest projectName 必须是非空字符串")
    if profile not in {"frontend", "generic"}:
        raise ValueError("manifest profile 必须是 frontend 或 generic")
    enabled = value.get("enabledPolicies", [])
    detected = value.get("detected", {})
    pending = value.get("pendingQuestions", [])
    if not isinstance(enabled, list) or not all(isinstance(item, str) for item in enabled):
        raise ValueError("manifest enabledPolicies 必须是字符串数组")
    if not isinstance(detected, dict) or not isinstance(pending, list):
        raise ValueError("manifest detected/pendingQuestions 类型错误")
    return Manifest(2, project_name, profile, tuple(enabled), detected, tuple(pending))


def _tokens(manifest: Manifest) -> dict[str, str]:
    return {"PROJECT_NAME": manifest.project_name, "PROJECT_SLUG": manifest.project_slug}


def render_tokens(text: str, manifest: Manifest) -> str:
    values = _tokens(manifest)

    def replace(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            raise ValueError(f"未知生成器变量：{key}")
        return values[key]

    return TOKEN_PATTERN.sub(replace, text)


def _frontmatter_end(lines: list[str]) -> int | None:
    if not lines or lines[0].strip() != "---":
        return None
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return index
    return None


def _body_without_frontmatter(text: str) -> str:
    lines = text.splitlines()
    end = _frontmatter_end(lines)
    body = lines[end + 1 :] if end is not None else lines
    return "\n".join(body).strip()


def mark_generated(text: str) -> str:
    normalized = text.rstrip() + "\n"
    lines = normalized.splitlines()
    end = _frontmatter_end(lines)
    if end is None:
        return f"{GENERATED_MARKER}\n{normalized}"
    frontmatter = "\n".join(lines[: end + 1])
    body = "\n".join(lines[end + 1 :]).lstrip()
    return f"{frontmatter}\n\n{GENERATED_MARKER}\n{body.rstrip()}\n"


def _source_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(
        (
            path
            for path in directory.rglob("*")
            if path.is_file() and not any(part in SKIP_NAMES for part in path.relative_to(directory).parts)
        ),
        key=lambda path: path.relative_to(directory).as_posix(),
    )


def _render_copy(path: Path, manifest: Manifest) -> bytes:
    content = path.read_bytes()
    if path.suffix.lower() not in {".md", ".mdc", ".txt"}:
        return content
    rendered = render_tokens(content.decode("utf-8"), manifest)
    return mark_generated(rendered).encode("utf-8")


def _combined_rules(cursor: Path, manifest: Manifest) -> bytes:
    sections: list[str] = []
    rule_directory = cursor / "rules"
    for path in _source_files(rule_directory):
        if path.suffix != ".mdc" or not path.name.startswith("core-"):
            continue
        text = render_tokens(path.read_text(encoding="utf-8"), manifest)
        body = _body_without_frontmatter(text)
        sections.append(f"<!-- source: .cursor/rules/{path.name} -->\n{body}")
    header = (
        "---\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{GENERATED_MARKER}\n"
        f"# {manifest.project_name} 项目规则\n\n"
    )
    return (header + "\n\n---\n\n".join(sections).rstrip() + "\n").encode("utf-8")


def render_generated_files(source_root: Path, target_root: Path, manifest: Manifest) -> dict[Path, bytes]:
    del target_root  # Reserved for target-aware rendering without coupling callers to future changes.
    cursor = source_root / ".cursor"
    generated: dict[Path, bytes] = {}
    rules = _combined_rules(cursor, manifest)
    rule_name = f"{manifest.project_slug}-project-rules.md"
    generated[Path(".codebuddy/rules") / rule_name] = rules
    generated[Path(".qoder/rules") / rule_name] = rules

    mirrors = (
        ("skills", (Path(".codebuddy/skills"), Path(".qoder/skills"))),
        ("snippets", (Path(".codebuddy/snippets"),)),
        ("context", (Path(".codebuddy/context"), Path(".qoder/context"))),
        ("prompts", (Path(".md/prompts"),)),
    )
    for source_name, destinations in mirrors:
        source_directory = cursor / source_name
        for source in _source_files(source_directory):
            relative = source.relative_to(source_directory)
            content = _render_copy(source, manifest)
            for destination in destinations:
                generated[destination / relative] = content
    return dict(sorted(generated.items(), key=lambda item: item[0].as_posix()))
